// <auto-generated />
using System;
using Hotel_Booking.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotel_Booking.Migrations.HotelBooking
{
    [DbContext(typeof(HotelBookingContext))]
    [Migration("20250123110503_AddPhotoUrlToChambreNew")]
    partial class AddPhotoUrlToChambreNew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hotel_Booking.Models.ChambreNew", b =>
                {
                    b.Property<int>("IdChambre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChambre"));

                    b.Property<int?>("Capacite")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionChambre")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StatutChambre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<double?>("TarifParNuit")
                        .HasColumnType("float");

                    b.Property<string>("TypeChambre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdChambre")
                        .HasName("PK__Chambre___50CF822B375F6A72");

                    b.ToTable("Chambre_New", (string)null);
                });

            modelBuilder.Entity("Hotel_Booking.Models.ReservationNew", b =>
                {
                    b.Property<int>("IdReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReservation"));

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateReservation")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdChambre")
                        .HasColumnType("int");

                    b.Property<string>("StatutReservation")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TypeReservation")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdReservation")
                        .HasName("PK__Reservat__7E69A57B7067A2D2");

                    b.HasIndex("IdChambre");

                    b.ToTable("Reservation_New", (string)null);
                });

            modelBuilder.Entity("Hotel_Booking.Models.ReservationNew", b =>
                {
                    b.HasOne("Hotel_Booking.Models.ChambreNew", "IdChambreNavigation")
                        .WithMany("ReservationNews")
                        .HasForeignKey("IdChambre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Reservati__IdCha__45F365D3");

                    b.Navigation("IdChambreNavigation");
                });

            modelBuilder.Entity("Hotel_Booking.Models.ChambreNew", b =>
                {
                    b.Navigation("ReservationNews");
                });
#pragma warning restore 612, 618
        }
    }
}
